name: shadowself-core

services:
  nginx:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/www/certbot:/var/www/certbot
    restart: always
    init: true

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    command: |
      sh -c '
        trap exit TERM;

        until certbot certonly --webroot -w /var/www/certbot --email contact@shadowself.io --no-eff-email  
          --agree-tos --non-interactive \
          -d shadowself.io \
          -d www.shadowself.io \
          -d mail.shadowself.io \
          -d us.shadowself.io \
          -d ca.shadowself.io \
          -d gb.shadowself.io \
          -d se.shadowself.io; do
            sleep 5;
          done

        while :; do
          certbot renew
          sleep 12h & wait $${!};
        done;
      '
    depends_on:
      - nginx
    restart: always
    init: true

  postgres:
    build: ./database
    expose:
      - 5432
    env_file:
      - ./database/.env
    volumes:
      - data:/var/lib/postgresql/data
    restart: always
    init: true

  backend:
    build: ./backend
    expose:
      - 3000
    env_file:
      - ./backend/.env
      - ./database/.env
    depends_on:
      - postgres
      - nginx
    restart: always
    init: true

  frontend:
    build: ./frontend
    expose:
      - 5000
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
      - nginx
    restart: always
    init: true

volumes:
  data:
