name: shadowself-proxies

services:
  nginx:
    build:
      context: ./nginx
      args:
        SUBDOMAIN: us
    ports:
      - 80:80
      - 443:443
    restart: always
    init: true

  openvpn:
    build: ./openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 3128:3128
    restart: always
    init: true

  squid:
    build: ./squid
    network_mode: service:openvpn
    depends_on:
      - openvpn
    volumes:
      - /etc/squid/passwd:/etc/squid/passwd:ro
    restart: always
    init: true

  server:
    build: ./src
    expose:
      - 4000
    env_file:
      - src/.env
    volumes:
      - /etc/squid/passwd:/etc/squid/passwd
    depends_on:
      - nginx
    restart: always
    init: true
