name: shadowself-proxies

services:
  nginx:
    build:
      context: ./nginx
      args:
        SUBDOMAIN: us
    ports:
      - 80:80
      - 443:443
    restart: always
    init: true

  openvpn:
    build: ./openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 3129:3129
      - 1080:1080
    restart: always
    init: true

  squid:
    build: ./squid
    network_mode: service:openvpn
    depends_on:
      - openvpn
    volumes:
      - squid-users:/etc/squid/passwd
    restart: always
    init: true

  dante:
    build: ./dante
    network_mode: service:openvpn
    depends_on:
      - openvpn
    volumes:
      - dante-passwd:/etc/passwd
      - dante-shadow:/etc/shadow
    restart: always
    init: true

  server:
    build: ./src
    expose:
      - 4000
    env_file:
      - src/.env
    volumes:
      - squid-users:/etc/squid/passwd
      - dante-passwd:/etc/passwd
      - dante-shadow:/etc/shadow
    depends_on:
      - nginx
    restart: always
    init: true

volumes:
  squid-users:
  dante-passwd:
  dante-shadow:
