const markets = [
  {
    name: 'KYCNOT.me',
    description: 'A curated list of non-KYC exchanges, services, and tools to preserve your identity.',
    tag: 'No-KYC',
    link: 'https://kycnot.me',
    icon: 'https://kycnot.me/favicon.svg',
    category: 'Directories',
  },
  {
    name: 'Monerica',
    description: 'The ultimate resource hub for the Monero economy and circular trade.',
    tag: 'Monero',
    link: 'https://monerica.com',
    icon: 'https://raw.githubusercontent.com/monero-project/monero-site/refs/heads/master/img/favicons.svg',
    category: 'Directories',
  },
  {
    name: 'Cryptwerk',
    description: 'A comprehensive directory of companies and services that accept cryptocurrencies.',
    tag: 'Directory',
    link: 'https://cryptwerk.com',
    icon: 'https://cryptwerk.com/tpl/img/icons/120x120-just-logo.png',
    category: 'Directories',
  },
  {
    name: 'ShopinBit',
    description: "Europe's largest crypto-exclusive store offering over 1 million products worldwide.",
    tag: 'E-commerce',
    link: 'https://shopinbit.com',
    icon: 'https://shopinbit.com/media/54/27/a8/1684356931/iconapple.png',
    category: 'Marketplaces',
  },
  {
    name: 'Spendabit',
    description: 'A search engine specifically designed to find products you can buy with Bitcoin.',
    tag: 'Search Engine',
    link: 'https://spendabit.co',
    icon: 'https://spendabit.co/img/spendabit-icon-md.png',
    category: 'Marketplaces',
  },
  {
    name: 'XMRbazaar',
    description: 'A peer-to-peer marketplace for buying and selling goods directly for Monero.',
    tag: 'P2P Market',
    link: 'https://xmrbazaar.com',
    icon: 'https://xmrbazaar.com/img/img_xmrbazaar_favicon.png',
    category: 'Marketplaces',
  },
  {
    name: 'Bitgild',
    description: 'Purchase physical gold and silver bars or coins using crypto with insured delivery.',
    tag: 'Precious Metals',
    link: 'https://www.bitgild.com',
    icon: 'https://www.bitgild.com/img/favicon/favicon-96x96.png',
    category: 'Financial Goods',
  },
  {
    name: 'CakePay',
    description: 'Instantly buy gift cards and prepaid Visa cards using XMR, BTC, or LTC.',
    tag: 'Gift Cards',
    link: 'https://cakepay.com',
    icon: 'https://cakepay.com/favicon.ico',
    category: 'Financial Goods',
  },
  {
    name: 'Anonshop',
    description: 'Proxy shopping service allowing you to buy from Amazon without exposing your identity.',
    tag: 'Proxy Shopping',
    link: 'https://anonshop.app',
    icon: 'https://raw.githubusercontent.com/DecentralizeJustice/Anonshop/refs/heads/main/src/assets/svg/box2.svg',
    category: 'Financial Goods',
  },
  {
    name: 'Coinsbee',
    description: 'Purchase gift cards, mobile top-ups, and payment cards with over 50 cryptocurrencies.',
    tag: 'Gift Cards',
    link: 'https://www.coinsbee.com',
    icon: 'https://cdn.coinsbee.com/dist/assets/favicon/favicon.ico',
    category: 'Financial Goods',
  },
  {
    name: 'RoboSats',
    description: 'A simple and private way to exchange Bitcoin for fiat currencies via Lightning Network.',
    tag: 'Lightning P2P',
    link: 'https://learn.robosats.org/',
    icon: 'https://unsafe.robosats.org/static/assets/images/favicon-192x192.png',
    category: 'On/Off Ramps',
  },
  {
    name: 'Bisq',
    description: 'A decentralized, open-source desktop application for buying and selling Bitcoin.',
    tag: 'DEX',
    link: 'https://bisq.network',
    icon: 'https://bisq.network/favicon.ico',
    category: 'On/Off Ramps',
  },
  {
    name: 'HodlHodl',
    description: 'A non-custodial Bitcoin exchange that uses multi-sig escrow for secure trades.',
    tag: 'Non-Custodial',
    link: 'https://hodlhodl.com',
    icon: 'https://hodlhodl.com/favicon.ico',
    category: 'On/Off Ramps',
  },
  {
    name: 'Njalla',
    description: 'A privacy-aware domain registration service that sits between you and the registrar.',
    tag: 'Domains',
    link: 'https://njal.la',
    icon: 'https://njal.la/favicon.ico',
    category: 'Sovereign Infrastructure',
  },
  {
    name: 'IncogNet',
    description: 'Privacy-focused web hosting, VPS, and domains accepting crypto payments.',
    tag: 'Hosting',
    link: 'https://incognet.io',
    icon: 'https://incognet.io/assets/icons/favicon.svg',
    category: 'Sovereign Infrastructure',
  },
  {
    name: 'Nostr',
    description: 'A decentralized network protocol for a censorship-resistant social media alternative.',
    tag: 'Protocol',
    link: 'https://nostr.com',
    icon: 'https://nostr.com/favicon.ico',
    category: 'Social Identity',
  },
  {
    name: 'Geyser Fund',
    description: 'A crowdfunding platform for creators and projects built on the Bitcoin Lightning Network.',
    tag: 'Crowdfunding',
    link: 'https://geyser.fund',
    icon: 'https://geyser.fund/logo-brand.svg',
    category: 'Social Identity',
  },
  {
    name: 'Matrix',
    description: 'An open standard for secure, decentralized, and real-time communication.',
    tag: 'Messaging',
    link: 'https://matrix.org',
    icon: 'https://matrix.org/assets/favicon.svg',
    category: 'Social Identity',
  },
  {
    name: 'Monerotopia',
    description: 'A community and conference dedicated to the Monero ecosystem and privacy tech.',
    tag: 'Community',
    link: 'https://monerotopia.com',
    icon: 'https://raw.githubusercontent.com/monero-project/monero-site/refs/heads/master/img/favicons.svg',
    category: 'Social Identity',
  },
];

export default markets;
