-- NOTHING SENSITIVE HERE, THIS IS JUST FOR INITIALIZATION OF THE DATABASE

-- Environment Variables
\set NAME `echo $POSTGRES_USER`
\set PASSWORD `echo $POSTGRES_PASSWORD`
\set DATABASE `echo $POSTGRES_DB`

-- Create Database
DROP DATABASE IF EXISTS :DATABASE;
CREATE DATABASE :DATABASE;
\connect :DATABASE;

-- Create User
DROP USER IF EXISTS :NAME;
CREATE USER :"NAME" WITH PASSWORD :'PASSWORD';

-- Grant Privileges
GRANT ALL privileges on database :DATABASE to :NAME;
ALTER DATABASE :DATABASE OWNER TO :NAME;
ALTER USER :NAME SUPERUSER;
