-- NOTHING SENSITIVE HERE, THIS IS JUST FOR INITIALIZATION OF THE DATABASE

-- Environment Variables
\set NAME `echo $POSTGRES_USER`
\set DATABASE `echo $POSTGRES_DB`

-- Grant Privileges
GRANT CONNECT ON DATABASE :DATABASE TO :"NAME";
GRANT USAGE ON SCHEMA public TO :"NAME";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO :"NAME";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO :"NAME";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"NAME";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO :"NAME";
DO $$
BEGIN
  IF current_user <> 'postgres' THEN
    EXECUTE format('ALTER USER %I NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION', current_user);
  END IF;
END;
$$;
