<script lang="ts">
  import type {Notification, Registration} from '$type';
  import {Steps, StepsItem} from '$component';
  import {currentStep} from '$store';
  import {notify} from '$lib';

  const {form}: {form: Notification & Registration} = $props();

  let qr = $state() as string;
  let secret = $state() as string;
  let username = $state() as string;
  let recovery = $state() as string[];
  let anchor = $state() as HTMLAnchorElement;

  $effect(() => {
    if (form?.message) notify(form.message, form.type);
    if (form?.step) currentStep.set(Number(form?.step));

    if (form?.username) username = form.username;
    if (form?.recovery) recovery = form.recovery;
    if (form?.secret) secret = form.secret;
    if (form?.qr) qr = form.qr;
  });

  function copyRecovery() {
    navigator.clipboard.writeText(recovery.join('\n'));
  }

  function downloadRecovery() {
    const text = recovery.join('\n');
    const blob = new Blob([text], {type: 'text/plain'});
    anchor.href = URL.createObjectURL(blob);
    anchor.click();
  }
</script>

<svelte:head>
  <title>ShadowSelf - Sign Up</title>
  <meta name="description" content="Sign up and create your account to start using ShadowSelf today" />
</svelte:head>

<Steps>
  <StepsItem index={1} action="init">
    <h1>Create an account</h1>
    <div class="flex gap-6">
      <label for="username">Username</label>
      <input type="text" placeholder="mountain eagle" name="username" required id="username" />
    </div>
    <div class="flex gap-6">
      <label for="password">Password</label>
      <input type="password" placeholder="correct horse battery staple" name="password" required id="password" />
    </div>
    <p>Already have an account? <a href="/login">Login</a></p>
    <button type="submit">Next</button>
  </StepsItem>
  <StepsItem index={2} action="askOTP">
    <h1>Hello {username},<br /> Would you like to enable 2FA now?</h1>
    <p>
      Two-Factor Authentication (2FA) is a security feature<br />
      that adds an extra layer of protection to your account when logging in
    </p>
    <button name="enable" type="submit">Enable 2FA</button>
    <button class="alt" name="skip" type="submit">Skip this step</button>
  </StepsItem>
  <StepsItem index={3} action="showOTP">
    <h1>Scan the QR code</h1>
    <img src={qr} alt="QR Code" width="300" />
    <div class="flex w-full flex-col gap-4">
      <p>Scan the QR code with your authenticator app (like Aegis)</p>
      <hr />
      <p>alternatively, you can paste this secret:<br /><b>{secret}</b></p>
      <p class="text-red-500">make sure to use 'SHA512' as the algorithm</p>
    </div>
    <button type="submit">Next</button>
  </StepsItem>
  <StepsItem index={4} action="checkOTP">
    <h1>Enter the verification token</h1>
    <p>Enter the verification token that was generated by your authenticator app</p>
    <input type="number" name="token" class="w-full" required />
    <button type="submit">Verify</button>
  </StepsItem>
  <StepsItem index={5} action="showRecovery">
    <h1>Store safely these recovery codes</h1>
    <p>
      Store these recovery codes somewhere safe, you will need<br />
      them to restore your account in case you lose access to your 2FA method.
    </p>
    <div class="grid grid-cols-2 gap-4 rounded-xl bg-slate-900/50 p-4">
      {#each recovery as code, index (index)}
        <p>{code}</p>
      {/each}
    </div>
    <div class="flex justify-evenly">
      <button type="button" onclick={copyRecovery} class="alt">Copy to clipboard</button>
      <button type="button" onclick={downloadRecovery} class="alt">Download as txt</button>
      <a bind:this={anchor} aria-label="Download" href="/" download="ShadowSelf-recovery-codes.txt" class="hidden"></a>
    </div>
    <button type="submit">Next</button>
  </StepsItem>
  <StepsItem index={6} action="askBilling">
    <h1>Would you like to add a billing method now?</h1>
    <p>
      You will need a payment method to use ShadowSelf<br />
      We accept both credit cards and crypto currency
    </p>
    <button name="add" type="submit">Add Payment</button>
    <button class="alt" name="skip" type="submit">Skip for now</button>
  </StepsItem>
  <StepsItem index={7} action="addBilling">
    <button type="submit">Add Billing</button>
  </StepsItem>
  <StepsItem index={8} action="create">
    <h1>And we're done!</h1>
    <p>
      Just click the button below<br />
      to finish setting up your account
    </p>
    <button type="submit">Create the account</button>
    <p class="-mb-6 text-sm text-neutral-400">
      By continuing, you agree to both our <br />
      <a href="/terms">Terms of Service</a> and <a href="/privacy-policy">Privacy Policy</a>
    </p>
  </StepsItem>
</Steps>

<style lang="postcss">
  h1 {
    @apply -mt-4 mb-4 text-4xl font-bold text-neutral-300;
  }

  img {
    @apply w-1/2 shadow-lg shadow-white/15;
  }

  input {
    @apply bg-slate-900/50;
  }
</style>
